# Generated by Django 5.0 on 2024-01-06 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('datepayment', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='actifaccount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
    ]
